### ISSUE TITLE
Milestones?

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#25]
Basically, what milestones should we set up?
Off the top of my head, I can definitely see "1.0" being a milestone, but I'm uncertain how far in the future that would be. What features would we consider to be in the 1.0 feature set?

**Comment by macluo** [comment]
How about something like game prototype, playable level, major feature completed, alpha release, beta, etc? The first milestone I can think of is to get every component in the game to work together.

**Comment by meneal** [comment]
Perhaps we're actually on the right side of the decimal point for now. :)  So maybe version 0.1?  I would say that these should be the main pieces for 0.1:

- Some simple main menu: nothing fancy
- One complete playable level 
- That complete playable level loads through the main index.html in the root directory of the repo, and the main menu loads and can actually load the game.
- Deploys to Heroku and plays on the public url

I'm leaving off the level editor and the procedural part of this since I think that's more 0.2 version stuff.  What do people think of that for a first milestone?

**Comment by duh102** [comment]
Do you think we could complete those before next Friday (or whenever we want to set the next milestone)?

**Comment by meneal** [comment]
I think it's possible, but we need to split up the work in some reasonable way to make it actually achievable.  I know the Heroku part is doable.  I just need to sit down and knock it out.  As far as a simple main menu, it seems like that should be doable too.  On the playable level part that I'm less sure of.  I think one thing that can be added in to this milestone is shifting all tests to mocha, that also should be fine to complete by Friday next week.

**Comment by meneal** [comment]
I would say whatever we set as a milestone should be by next Friday, since we have a limited time frame and we should have at least a few milestones I'd think.

**Comment by duh102** [comment]
In that case, perhaps the immediate milestones could be:
### Friday 02/27
* Functional, if not pretty main menu
* Main menu loads (at least one) level
* Once you reach the end of the level, game tells you you've finished the level
* Can deploy the entire thing to Heroku in an automated fashion on git commits (but only when all tests pass)

### Friday 03/06
* Functional menu that can choose more than one level
* Editor
* Naive/uninteresting procedural gen mazes?

**Comment by duh102** [comment]
Going to take no disagreement as implicit agreement, I'll put these tentative milestones up and we can modify as necessary.

**Comment by meneal** [comment]
I think that makes sense.

**Comment by macluo** [comment]
I agree. :+1:
