### ISSUE TITLE
Automate copying files to public folder

### ISSUE THREAD

**Issue by macluo** [CSC510-2015-Axitron/maze#47]
Not sure if this has been planned but a feature like this would be nice.

**Comment by meneal** [comment]
This is a good idea for sure.  I think it can be done with grunt actually.
The only problem I see is knowing which files should be checked for
changes.  I guess if it is tested by mocha, and passes, and there is a
difference between what is in public and what is in the root a copy over
will occur?

**Comment by macluo** [comment]
Just saw your [comment](https://github.com/CSC510-2015-Axitron/maze/issues/40#issuecomment-81255096) on #40. If we have Heroku, cleaning up the Divshot stuffs would be a good idea.

**Comment by meneal** [comment]
So the thing about that is that everything should probably stay as is on
Heroku.  The site loads from the public folder still.  I think we can clean
out a bunch of the data stuff that's in there.

**Comment by macluo** [comment]
While reviewing week1 materials I realize this task could be achieved with a Makefile.

**Comment by duh102** [comment]
It could be, but we're not using Make so far in this project and I think one of the other things we use (Travis maybe?) can do it.

**Comment by macluo** [comment]
We could add "make" command in package.json so make will look for Makefile when test is completed.

**Comment by meneal** [comment]
I think that some of this can be done using grunt.  Since it minifies code,
I'm assuming that during that process you can set it's target since you
wouldn't want those messy files hanging around in your development version
of the code.  I haven't used grunt excessively, but this type of thing is
definitely the usecase for it.  Travis will support grunt too so there's
also that.

**Comment by duh102** [comment]
I can take a poke at this, if nobody else is looking into it. Is it easy to give me travis access?

**Comment by duh102** [comment]
Nvm I think I already have access, just didn't know that you configured your task via the repo's .travis file.

**Comment by meneal** [comment]
If you haven't gotten too far yet I can take this when the side menu is
done.  I wanted to learn grunt anyway.

**Comment by duh102** [comment]
I've been working on reorganizing everything to make it neater and so it can minifiy it all, no idea if it works yet.

**Comment by duh102** [comment]
Could someone look over 818d55a39c7ca373a1df91caa1ebb21410007a45 and see if it's all ok? I don't think I've done anything destructive, as far as I can tell everything still works (tested on my local server), both minifying and copying steps.
The only thing I had to actually change, program-wise, was the address for axemaze-db to https, a small thing I found out while testing since I use https on my server. Turns out Firefox doesn't like it if you are using https to access a site and the site attempts to use ajax on an http address. Going from an http to an https is no problem, though.
