### ISSUE TITLE
Checkmarks for completed mazes in sidemenu

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#73]
As title (probably using utf8 dingbat: http://www.w3schools.com/charsets/ref_utf_dingbats.asp )

**Comment by meneal** [comment]
This is done.  I also took Will's suggestion and update the usermazes when this happens too.  Performance is ok for now.  We have to change some stuff around should performance be further be degraded by tons of api calls.  I did notice one thing that I'll put into a bug report.  Since the sidemenu stuff isn't integrated completely into the other calls that mazeMenu was using when a level is completed it isn't added into a logged in user's information.
